# Generated by Django 5.1.6 on 2025-04-15 21:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='module',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/courses/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/lessons/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='content_type',
            field=models.CharField(choices=[('TEXT', 'Текст'), ('VIDEO', 'Видео'), ('IMAGE', 'Изображение'), ('GIF', 'GIF-анимация'), ('FILE', 'Файл')], max_length=5),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contents/files/'),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='gif',
            field=models.FileField(blank=True, null=True, upload_to='contents/gifs/'),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contents/images/'),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courses.lesson'),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
