# Generated by Django 5.1.6 on 2025-04-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson_description_module_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='type',
            field=models.CharField(choices=[('ARTICLE', 'Статья'), ('LAB', 'Лабораторная работа'), ('PRACTICE', 'Практика')], default='ARTICLE', max_length=20),
        ),
    ]
