# Generated by Django 5.1.6 on 2025-04-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncontent',
            name='code_language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lessoncontent',
            name='quiz_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lessoncontent',
            name='table_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='content_type',
            field=models.CharField(choices=[('TEXT', 'Текст'), ('VIDEO', 'Видео'), ('IMAGE', 'Изображение'), ('GIF', 'GIF-анимация'), ('FILE', 'Файл'), ('CODE', 'Код'), ('QUIZ', 'Тест'), ('TABLE', 'Таблица')], max_length=10),
        ),
    ]
