# Generated by Django 5.1.6 on 2025-04-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lessoncontent_code_language_lessoncontent_quiz_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessoncontent',
            name='gif',
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='content_type',
            field=models.CharField(choices=[('TEXT', 'Текст'), ('VIDEO', 'Видео'), ('IMAGE', 'Изображение'), ('FILE', 'Файл'), ('CODE', 'Код'), ('QUIZ', 'Тест'), ('TABLE', 'Таблица')], max_length=10),
        ),
    ]
