# Generated by Django 5.1.6 on 2025-05-10 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_comments'),
        ('courses', '0006_remove_lessoncontent_gif_and_more'),
    ]

    operations = [
    ]
