# Generated by Django 5.2 on 2025-05-30 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_recreate_aichatstate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='content',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='user',
        ),
        migrations.DeleteModel(
            name='AIChatState',
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
