# Generated by Django 5.2 on 2025-05-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_usercourseprogress_lessoncompletion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncompletion',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
