# Generated by Django 5.1.6 on 2025-05-10 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_merge_20250510_1836'),
        ('courses', '0009_add_is_edited_field'),
    ]

    operations = [
    ]
