# Generated by Django 4.2.7 on 2025-05-11 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_comment_likes_count_comment_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies_to_me', to='courses.comment'),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes_count',
        ),
    ]
