# Generated by Django 4.2.7 on 2025-05-11 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20250511_1955'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE courses_comment DROP COLUMN IF EXISTS reply_to_id;
            """,
            """
            -- No reverse SQL needed as we're dropping a column that doesn't exist
            """
        ),
    ]
