# Generated by Django 5.1.6 on 2025-05-11 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20250511_2000'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Remove these operations since the fields already exist
        # migrations.RemoveField(
        #     model_name='comment',
        #     name='reply_to',
        # ),
        # migrations.AddField(
        #     model_name='comment',
        #     name='likes_count',
        #     field=models.IntegerField(default=0),
        # ),
        
        migrations.AddField(
            model_name='lessoncontent',
            name='max_score',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='content_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('FILE', 'File'), ('CODE', 'Code Exercise'), ('QUIZ', 'Quiz')], max_length=10),
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='courses.lessoncontent')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['completed_at'],
                'unique_together': {('user', 'lesson', 'content')},
            },
        ),
    ]
