# Generated by Django 5.2 on 2025-05-30 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='customform',
            name='contents',
            field=models.ManyToManyField(related_name='forms', to='content.content'),
        ),
        migrations.AddField(
            model_name='customform',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_forms', to='courses.lesson'),
        ),
        migrations.AlterUniqueTogether(
            name='content',
            unique_together={('lesson', 'order')},
        ),
    ]
