# Generated by Django 5.1.6 on 2025-03-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_user_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='course',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
