# Generated by Django 5.1.6 on 2025-04-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_alter_user_group_alter_user_middle_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='reset_code_created_at',
            new_name='email_verification_code_expires',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reset_code',
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='new_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
